# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Menu(object):
    def setupUi(self, Ventana_Menu):
        Ventana_Menu.setObjectName("Ventana_Menu")
        Ventana_Menu.resize(810, 523)
        Ventana_Menu.setMinimumSize(QtCore.QSize(810, 523))
        Ventana_Menu.setMaximumSize(QtCore.QSize(810, 523))
        self.centralwidget = QtWidgets.QWidget(Ventana_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Imagen_Menu = QtWidgets.QLabel(self.centralwidget)
        self.label_Imagen_Menu.setGeometry(QtCore.QRect(-4, -8, 821, 491))
        self.label_Imagen_Menu.setText("")
        self.label_Imagen_Menu.setObjectName("label_Imagen_Menu")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 310, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        Ventana_Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ventana_Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        Ventana_Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ventana_Menu)
        self.statusbar.setObjectName("statusbar")
        Ventana_Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Ventana_Menu)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Menu)

    def retranslateUi(self, Ventana_Menu):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Menu.setWindowTitle(_translate("Ventana_Menu", "MainWindow"))
        self.pushButton.setText(_translate("Ventana_Menu", "Crear grupo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Menu = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Menu()
    ui.setupUi(Ventana_Menu)
    Ventana_Menu.show()
    sys.exit(app.exec_())
