# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap


import Python.view.resource as rsc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: #c0e1ec;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 182, 1080))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("background-color: #01233C;")   
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(20, 0, 100, 100))
        self.pushButton.setObjectName("pushButton")
        #Establecer la imagen del boton
        icon = QIcon()
        icon.addPixmap(QPixmap(rsc.resource_path("resources/Iconos/Exterior.png")), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        # Establecer propiedades del botón
        # Hacer que la imagen tenga animacion al ser presionada
        self.pushButton.setFlat(True) 
        self.pushButton.setStyleSheet("background-color: transparent;")  # Hace que el fondo del botón sea transparente
        
        # cambiar el tamaño de la imagen
        self.pushButton.setIconSize(QtCore.QSize(100, 100))  # Cambia el tamaño del icono del botón
        
        # Boton Para ir a la seccion de grupos
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 210, 100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(rsc.resource_path("resources/Iconos/User_Groups_Icon.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setStyleSheet("background-color: transparent;")
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        
        #Frame para la barra lateral de arriba
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: #01233C;")
        self.frame.setGeometry(QtCore.QRect(169, -6, 1751, 104))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        #Frame para la parte de creacion de grupos

        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(231, 188, 754, 770))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setStyleSheet("background-color: #004B73; border-radius: 30px;")
        
        #Boton para crear grupos

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 40, 100, 100))
        self.pushButton_3.setObjectName("pushButton_3")
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(rsc.resource_path("resources/Iconos/Añadir_Grupo_De_Usuarios_Hombre_Hombre.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(100, 100))

        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setGeometry(QtCore.QRect(60, 168, 619, 530))
        self.widget_2.setObjectName("widget_2")
        self.widget_2.setStyleSheet("background-color: #C0E1EC; border-radius: 0px;")   
        self.label_Nombre_Grupo = QtWidgets.QLabel(self.widget_2)
        self.label_Nombre_Grupo.setGeometry(QtCore.QRect(50, 10, 1000, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Nombre_Grupo.setFont(font)
        self.label_Nombre_Grupo.setStyleSheet("color: #01233C;")
        self.label_Nombre_Grupo.setObjectName("label_Nombre_Grupo")
        self.line_Nombre_Grupo = QtWidgets.QLineEdit(self.widget_2)
        self.line_Nombre_Grupo.setGeometry(QtCore.QRect(50, 50, 514, 64))
        self.line_Nombre_Grupo.setObjectName("lineNombre_Grupo")
        self.line_Nombre_Grupo.setStyleSheet("background-color: #66ADCC;")
        self.line_Nombre_Grupo.setFont(font)
        self.label_Añadir_Miembros = QtWidgets.QLabel(self.widget_2)
        self.label_Añadir_Miembros.setGeometry(QtCore.QRect(50, 130, 1000, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Añadir_Miembros.setFont(font)
        self.label_Añadir_Miembros.setStyleSheet("color: #01233C;")
        self.label_Añadir_Miembros.setObjectName("label_Añadir_Miembros")

        self.widget_CheckBox = QtWidgets.QWidget(self.widget_2)
        self.widget_CheckBox.setGeometry(QtCore.QRect(50, 180, 514, 300))
        self.widget_CheckBox.setObjectName("widget_CheckBox")
        self.widget_CheckBox.setStyleSheet("background-color: #66ADCC;")

        self.checkBox_1 = QtWidgets.QCheckBox(self.widget_CheckBox)
        self.checkBox_1.setGeometry(QtCore.QRect(10, 10, 500, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_1.setText("Usuario disponible")
        self.checkBox_1.setStyleSheet("color: #01233C;")

        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_CheckBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 80, 500, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.setText("Usuario disponible")
        self.checkBox_2.setStyleSheet("color: #01233C;")

        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_CheckBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 150, 500, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.setText("Usuario disponible")
        self.checkBox_3.setStyleSheet("color: #01233C;")

        ##Frame para la seleccion de grupos y lista de miembros
        
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(1094, 188, 754, 770))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setStyleSheet("background-color: #004B73; border-radius: 30px;")

        ##Icono para ver los grupos

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 40, 100, 100))
        self.pushButton_4.setObjectName("pushButton_4")
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(rsc.resource_path("resources/Iconos/Conferencia.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(100, 100))

        ##Widget para la lista de grupos
        self.widget_3 = QtWidgets.QWidget(self.frame_3)
        self.widget_3.setGeometry(QtCore.QRect(60, 140, 619, 274))
        self.widget_3.setObjectName("widget_3")
        self.widget_3.setStyleSheet("background-color: #C0E1EC; border-radius: 0px;")

        #Agregar un QScrollArea
        self.scrollArea = QtWidgets.QScrollArea(self.widget_3)
        self.scrollArea.setGeometry(QtCore.QRect(50, 50, 651, 671))
        self.scrollArea.setObjectName("scrollArea")
        
        #Lista para widget_3 con los grupos
        self.listWidget = QtWidgets.QListWidget()
        self.listWidget.setGeometry(QtCore.QRect(50, 50, 600, 180))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.listWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget {color: #01233C;}")
        
        
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        self.widget_4.setGeometry(QtCore.QRect(60, 450, 619, 274))
        self.widget_4.setObjectName("widget_4")
        self.widget_4.setStyleSheet("background-color: #C0E1EC; border-radius: 0px;")

       
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " "))
        self.pushButton_2.setText(_translate("MainWindow", " "))
        self.pushButton_3.setText(_translate("MainWindow", " "))
        self.pushButton_4.setText(_translate("MainWindow", " "))
        #self.pushButton_5.setText(_translate("MainWindow", "GRUPO EPICO 1"))
        self.label_Nombre_Grupo.setText(_translate("MainWindow", "NOMBRE DEL GRUPO"))
        self.label_Añadir_Miembros.setText(_translate("MainWindow", "AÑADIR MIEMBROS"))
        self.checkBox_1.setText(_translate("MainWindow", "USUARIO DISPONIBLE"))
        self.checkBox_2.setText(_translate("MainWindow", "USUARIO DISPONIBLE"))
        self.checkBox_3.setText(_translate("MainWindow", "USUARIO DISPONIBLE"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
