# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Eventos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_AdminGrupos(object):
    def setupUi(self, Ventana_AdminGrupos):
        Ventana_AdminGrupos.setObjectName("Ventana_AdminGrupos")
        Ventana_AdminGrupos.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(Ventana_AdminGrupos)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 182, 1080))
        self.widget.setStyleSheet("background-color: #01233C;")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(20, 0, 100, 100))
        self.pushButton.setStyleSheet("background-color: transparent;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/Exterior.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.Boton_CrearGrupo = QtWidgets.QPushButton(self.widget)
        self.Boton_CrearGrupo.setGeometry(QtCore.QRect(20, 210, 100, 100))
        self.Boton_CrearGrupo.setStyleSheet("background-color: transparent;")
        self.Boton_CrearGrupo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/User_Groups_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_CrearGrupo.setIcon(icon1)
        self.Boton_CrearGrupo.setIconSize(QtCore.QSize(100, 100))
        self.Boton_CrearGrupo.setFlat(True)
        self.Boton_CrearGrupo.setObjectName("Boton_CrearGrupo")
        self.Boton_Chat = QtWidgets.QPushButton(self.widget)
        self.Boton_Chat.setGeometry(QtCore.QRect(30, 390, 100, 100))
        self.Boton_Chat.setStyleSheet("background-color: transparent;")
        self.Boton_Chat.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/inicioSesion/Icons/Chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_Chat.setIcon(icon2)
        self.Boton_Chat.setIconSize(QtCore.QSize(100, 100))
        self.Boton_Chat.setFlat(True)
        self.Boton_Chat.setObjectName("Boton_Chat")
        self.Boton_Eventos = QtWidgets.QPushButton(self.widget)
        self.Boton_Eventos.setGeometry(QtCore.QRect(30, 580, 100, 100))
        self.Boton_Eventos.setStyleSheet("background-color: transparent;")
        self.Boton_Eventos.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/inicioSesion/Icons/Evento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Boton_Eventos.setIcon(icon3)
        self.Boton_Eventos.setIconSize(QtCore.QSize(100, 100))
        self.Boton_Eventos.setFlat(True)
        self.Boton_Eventos.setObjectName("Boton_Eventos")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(169, -6, 1751, 104))
        self.frame.setStyleSheet("background-color: #01233C;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(231, 188, 1591, 770))
        self.frame_2.setStyleSheet("background-color: #004B73; border-radius: 30px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setGeometry(QtCore.QRect(60, 127, 1451, 571))
        self.widget_2.setStyleSheet("background-color: #C0E1EC; border-radius: 0px;")
        self.widget_2.setObjectName("widget_2")
        self.label_Nombre_Grupo = QtWidgets.QLabel(self.widget_2)
        self.label_Nombre_Grupo.setGeometry(QtCore.QRect(50, 10, 1000, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Nombre_Grupo.setFont(font)
        self.label_Nombre_Grupo.setStyleSheet("color: #01233C;")
        self.label_Nombre_Grupo.setText("")
        self.label_Nombre_Grupo.setObjectName("label_Nombre_Grupo")
        Ventana_AdminGrupos.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ventana_AdminGrupos)
        QtCore.QMetaObject.connectSlotsByName(Ventana_AdminGrupos)

    def retranslateUi(self, Ventana_AdminGrupos):
        _translate = QtCore.QCoreApplication.translate
        Ventana_AdminGrupos.setWindowTitle(_translate("Ventana_AdminGrupos", "MainWindow"))
import imagenesInicioSesion_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_AdminGrupos = QtWidgets.QMainWindow()
    ui = Ui_Ventana_AdminGrupos()
    ui.setupUi(Ventana_AdminGrupos)
    Ventana_AdminGrupos.show()
    sys.exit(app.exec_())
