# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Ingreso.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import resources.QRC.images
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Window_Inicio(object):
    def setupUi(self, Window_Inicio):
        Window_Inicio.setObjectName("Window_Inicio")
        Window_Inicio.resize(800, 536)
        Window_Inicio.setMinimumSize(QtCore.QSize(800, 536))
        Window_Inicio.setMaximumSize(QtCore.QSize(800, 536))
        self.centralwidget = QtWidgets.QWidget(Window_Inicio)
        self.centralwidget.setStyleSheet("background-color:#01233C")
        self.centralwidget.setObjectName("centralwidget")
        self.Line_Usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Usuario.setGeometry(QtCore.QRect(215, 300, 370, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Line_Usuario.setFont(font)
        self.Line_Usuario.setStyleSheet(
            "background-color:#FFFFFF; color:#01233C; border-radius:10px")
        self.Line_Usuario.setText("")
        self.Line_Usuario.setCursorPosition(0)
        self.Line_Usuario.setReadOnly(False)
        self.Line_Usuario.setObjectName("Line_Usuario")
        self.Line_Contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Contrasena.setGeometry(QtCore.QRect(215, 364, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Line_Contrasena.setFont(font)
        self.Line_Contrasena.setStyleSheet(
            "background-color:#FFFFFF; color:#01233C; border-radius:10px")
        self.Line_Contrasena.setInputMask("")
        self.Line_Contrasena.setMaxLength(12)
        self.Line_Contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Line_Contrasena.setReadOnly(False)
        self.Line_Contrasena.setPlaceholderText(" Contraseña")
        self.Line_Contrasena.setObjectName("Line_Contrasena")
        self.Ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.Ingresar.setGeometry(QtCore.QRect(324, 404, 146, 45))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Ingresar.setFont(font)
        self.Ingresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ingresar.setStyleSheet("QPushButton{\n"
                                    "    background-color:#FFFFFF; \n"
                                    "    color:#01233C; \n"
                                    "    border-radius:20px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover{\n"
                                    "    background-color:#01233C; \n"
                                    "    color:#FFFFFF; \n"
                                    "    border-radius:20px;\n"
                                    "}")
        self.Ingresar.setIconSize(QtCore.QSize(20, 16))
        self.Ingresar.setObjectName("Ingresar")
        self.Boton_Cracion_Usuario = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Cracion_Usuario.setEnabled(True)
        self.Boton_Cracion_Usuario.setGeometry(QtCore.QRect(355, 456, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_Cracion_Usuario.setFont(font)
        self.Boton_Cracion_Usuario.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Cracion_Usuario.setAcceptDrops(False)
        self.Boton_Cracion_Usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Boton_Cracion_Usuario.setStyleSheet("QPushButton{\n"
                                                 "    color: #FFFFFF; \n"
                                                 "    background-color: transparent; \n"
                                                 "    border-radius:10px;\n"
                                                 "}\n"
                                                 "QPushButton:hover{\n"
                                                 "    color: #00EEFF; \n"
                                                 "    background-color: transparent; \n"
                                                 "    border-radius:10px;\n"
                                                 "}\n"
                                                 "")
        self.Boton_Cracion_Usuario.setObjectName("Boton_Cracion_Usuario")
        self.Label_Imagen = QtWidgets.QLabel(self.centralwidget)
        self.Label_Imagen.setEnabled(True)
        self.Label_Imagen.setGeometry(QtCore.QRect(-20, 0, 976, 541))
        self.Label_Imagen.setAutoFillBackground(False)
        self.Label_Imagen.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.Label_Imagen.setText("")
        self.Label_Imagen.setPixmap(QtGui.QPixmap(
            ":/newPrefix/Images/viejito-01.png"))
        self.Label_Imagen.setScaledContents(True)
        self.Label_Imagen.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.Label_Imagen.setObjectName("Label_Imagen")
        self.Label_Usuario = QtWidgets.QLabel(self.centralwidget)
        self.Label_Usuario.setGeometry(QtCore.QRect(220, 268, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Usuario.setFont(font)
        self.Label_Usuario.setStyleSheet(
            "color: #FFFFFF; background-color: transparent;")
        self.Label_Usuario.setObjectName("Label_Usuario")
        self.Label_Contrasena = QtWidgets.QLabel(self.centralwidget)
        self.Label_Contrasena.setGeometry(QtCore.QRect(220, 332, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Contrasena.setFont(font)
        self.Label_Contrasena.setStyleSheet(
            "color: #FFFFFF; background-color: transparent;")
        self.Label_Contrasena.setObjectName("Label_Contrasena")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(-20, -20, 831, 535))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(34)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(
            "background-image: url(:/newPrefix/Fondo.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Fondo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Boton_Cambio_Contra = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Cambio_Contra.setGeometry(QtCore.QRect(310, 481, 180, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Boton_Cambio_Contra.setFont(font)
        self.Boton_Cambio_Contra.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_Cambio_Contra.setStyleSheet(
            "color: #FFFFFF; background-color: transparent; border-radius:10px")
        self.Boton_Cambio_Contra.setObjectName("Boton_Cambio_Contra")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(337, 80, 126, 160))
        self.logo.setStyleSheet("background-color: transparent;")
        self.logo.setFrameShape(QtWidgets.QFrame.Box)
        self.logo.setLineWidth(0)
        self.logo.setPixmap(QtGui.QPixmap(":/inicioSesion/Icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label.raise_()
        self.Label_Imagen.raise_()
        self.Line_Usuario.raise_()
        self.Line_Contrasena.raise_()
        self.Ingresar.raise_()
        self.Boton_Cracion_Usuario.raise_()
        self.Label_Usuario.raise_()
        self.Label_Contrasena.raise_()
        self.Boton_Cambio_Contra.raise_()
        self.logo.raise_()
        Window_Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_Inicio)
        QtCore.QMetaObject.connectSlotsByName(Window_Inicio)

    def retranslateUi(self, Window_Inicio):
        _translate = QtCore.QCoreApplication.translate
        Window_Inicio.setWindowTitle(_translate("Window_Inicio", "MainWindow"))
        self.Line_Usuario.setPlaceholderText(
            _translate("Window_Inicio", " Correo"))
        self.Ingresar.setText(_translate("Window_Inicio", "Ingresar"))
        self.Boton_Cracion_Usuario.setText(
            _translate("Window_Inicio", "Registrarse"))
        self.Label_Usuario.setText(_translate("Window_Inicio", "Correo "))
        self.Label_Contrasena.setText(
            _translate("Window_Inicio", "Contraseña"))
        self.Boton_Cambio_Contra.setText(_translate(
            "Window_Inicio", "¿Olvidaste tu contraseña?"))

    def set_image_opacity(self, value):
        graphics_effect = QtWidgets.QGraphicsOpacityEffect(self.Label_Imagen)
        graphics_effect.setOpacity(value)
        self.Label_Imagen.setGraphicsEffect(graphics_effect)



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Window_Inicio = QtWidgets.QMainWindow()
    ui = Ui_Window_Inicio()
    ui.setupUi(Window_Inicio)
    ui.set_image_opacity(0.44)
    Window_Inicio.show()
    sys.exit(app.exec_())
