# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Codigo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Codigo(object):
    def setupUi(self, Window_Codigo):
        Window_Codigo.setObjectName("Window_Codigo")
        Window_Codigo.resize(709, 493)
        self.centralwidget = QtWidgets.QWidget(Window_Codigo)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Imagen = QtWidgets.QLabel(self.centralwidget)
        self.Label_Imagen.setGeometry(QtCore.QRect(-10, -10, 831, 501))
        self.Label_Imagen.setAutoFillBackground(False)
        self.Label_Imagen.setText("")
        self.Label_Imagen.setPixmap(QtGui.QPixmap("img\Fondo.png"))
        self.Label_Imagen.setScaledContents(True)
        self.Label_Imagen.setObjectName("Label_Imagen")
        self.tituloCodigo = QtWidgets.QLabel(self.centralwidget)
        self.tituloCodigo.setGeometry(QtCore.QRect(190, 100, 341, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        self.tituloCodigo.setFont(font)
        self.tituloCodigo.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloCodigo.setObjectName("tituloCodigo")
        self.line_Codigo = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Codigo.setGeometry(QtCore.QRect(250, 180, 221, 61))
        self.line_Codigo.setReadOnly(False)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(20)
        self.line_Codigo.setFont(font)
        self.line_Codigo.setObjectName("line_Codigo")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(370, 280, 101, 31))
        self.okButton.setObjectName("okButton")
        self.textoIncorrecto = QtWidgets.QLabel(self.centralwidget)
        self.textoIncorrecto.setGeometry(QtCore.QRect(210, 380, 301, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.textoIncorrecto.setFont(font)
        self.textoIncorrecto.setStyleSheet("color: rgb(224, 27, 36);")
        self.textoIncorrecto.setAlignment(QtCore.Qt.AlignCenter)
        self.textoIncorrecto.setObjectName("textoIncorrecto")
        self.atrasButton = QtWidgets.QPushButton(self.centralwidget)
        self.atrasButton.setGeometry(QtCore.QRect(250, 280, 101, 31))
        self.atrasButton.setObjectName("atrasButton")
        Window_Codigo.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_Codigo)
        QtCore.QMetaObject.connectSlotsByName(Window_Codigo)

        # trigger
        self.line_Codigo.returnPressed.connect(self.mostrar_texto)
        self.okButton.clicked.connect(self.mostrar_texto)
    
    def mostrar_texto(self):
        return self.line_Codigo.text()

    def retranslateUi(self, Window_Codigo):
        _translate = QtCore.QCoreApplication.translate
        Window_Codigo.setWindowTitle(_translate("Window_Codigo", "MainWindow"))
        self.tituloCodigo.setText(_translate("Window_Codigo", "Por favor digita el codigo que te \n"
"mandamos al correo:"))
        self.okButton.setText(_translate("Window_Codigo", "OK"))
        self.textoIncorrecto.setText(_translate("Window_Codigo", "Codigo incorrecto, intenta de nuevo"))
        self.atrasButton.setText(_translate("Window_Codigo", "Ir atrás"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_Codigo = QtWidgets.QMainWindow()
    ui = Ui_Window_Codigo()
    ui.setupUi(Window_Codigo)
    Window_Codigo.show()
    sys.exit(app.exec_())
