# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Cambio_Rec_Contra.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Cambio_Rec_contra(object):
    def setupUi(self, Ventana_Cambio_Rec_contra):
        Ventana_Cambio_Rec_contra.setObjectName("Ventana_Cambio_Rec_contra")
        Ventana_Cambio_Rec_contra.resize(810, 523)
        Ventana_Cambio_Rec_contra.setMinimumSize(QtCore.QSize(810, 523))
        Ventana_Cambio_Rec_contra.setMaximumSize(QtCore.QSize(810, 523))
        self.centralwidget = QtWidgets.QWidget(Ventana_Cambio_Rec_contra)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Fondo_Cambio_Rec_Contra = QtWidgets.QLabel(self.centralwidget)
        self.Label_Fondo_Cambio_Rec_Contra.setGeometry(QtCore.QRect(-30, -20, 851, 531))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Label_Fondo_Cambio_Rec_Contra.setFont(font)
        self.Label_Fondo_Cambio_Rec_Contra.setText("")
        self.Label_Fondo_Cambio_Rec_Contra.setObjectName("Label_Fondo_Cambio_Rec_Contra")
        self.Label_Cambio_Rec_Contra = QtWidgets.QLabel(self.centralwidget)
        self.Label_Cambio_Rec_Contra.setGeometry(QtCore.QRect(240, 90, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Cambio_Rec_Contra.setFont(font)
        self.Label_Cambio_Rec_Contra.setObjectName("Label_Cambio_Rec_Contra")
        self.Line_Cambio_Rec_Contra = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Cambio_Rec_Contra.setGeometry(QtCore.QRect(240, 180, 311, 31))
        self.Line_Cambio_Rec_Contra.setObjectName("Line_Cambio_Rec_Contra")
        self.Boton_Regresar_Cambio_Rec_Contra = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Regresar_Cambio_Rec_Contra.setGeometry(QtCore.QRect(180, 310, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_Regresar_Cambio_Rec_Contra.setFont(font)
        self.Boton_Regresar_Cambio_Rec_Contra.setObjectName("Boton_Regresar_Cambio_Rec_Contra")
        self.Boton_Avanzar_Cambio_Rec_Contra = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Avanzar_Cambio_Rec_Contra.setGeometry(QtCore.QRect(410, 310, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_Avanzar_Cambio_Rec_Contra.setFont(font)
        self.Boton_Avanzar_Cambio_Rec_Contra.setObjectName("Boton_Avanzar_Cambio_Rec_Contra")
        Ventana_Cambio_Rec_contra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ventana_Cambio_Rec_contra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        Ventana_Cambio_Rec_contra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ventana_Cambio_Rec_contra)
        self.statusbar.setObjectName("statusbar")
        Ventana_Cambio_Rec_contra.setStatusBar(self.statusbar)

        self.retranslateUi(Ventana_Cambio_Rec_contra)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Cambio_Rec_contra)

    def retranslateUi(self, Ventana_Cambio_Rec_contra):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Cambio_Rec_contra.setWindowTitle(_translate("Ventana_Cambio_Rec_contra", "MainWindow"))
        self.Label_Cambio_Rec_Contra.setText(_translate("Ventana_Cambio_Rec_contra", "Ingrese la nueva contraseña"))
        self.Boton_Regresar_Cambio_Rec_Contra.setText(_translate("Ventana_Cambio_Rec_contra", "Regresar"))
        self.Boton_Avanzar_Cambio_Rec_Contra.setText(_translate("Ventana_Cambio_Rec_contra", "Cambiar contraseña"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Cambio_Rec_contra = QtWidgets.QMainWindow()
    ui = Ui_Ventana_Cambio_Rec_contra()
    ui.setupUi(Ventana_Cambio_Rec_contra)
    Ventana_Cambio_Rec_contra.show()
    sys.exit(app.exec_())
